/** Provides the cached Git describe version string.
 *
 * Reads the generated build artifact and returns the trimmed version string for
 * display in the window title and diagnostics. The build artifact itself is
 * generated by scripts/git_describe_version.d.
 *
 * See_Also:
 *   scripts/git_describe_version.d
 *
 * Authors: Carsten Schlote, schlote@vahanus.net
 * Copyright: Carsten Schlote, Released under CC-BY-NC-SA 4.0 license, 2018
 * License: CC-BY-NC-SA 4.0
 */
module version_info;

import std.string : strip;

private enum gitDescribeVersion = import("build/git-describe.txt").strip;

/** Returns the cached Git describe version string from the generated build artifact.
 *
 * @returns The trimmed Git describe version string.
 */
string getGitDescribeVersion()
{
    return gitDescribeVersion.idup;
}